// 音階・スケール関連ユーティリティ
// util.tsから移動した関数
export const getScaleNoteNames = (scale: string) => {
  const scaleMap: { [key: string]: string[] } = {
    C: ["C", "D", "E", "F", "G", "A", "B"],
    Cm: ["C", "D", "E♭", "F", "G", "A♭", "B♭"],
    "C＃": ["C＃", "D＃", "E＃", "F＃", "G＃", "A＃", "B＃"],
    "C＃m": ["C＃", "D＃", "E", "F＃", "G＃", "A", "B"],
    "C♭": ["C♭", "D♭", "E♭", "F♭", "G♭", "A♭", "B♭"],
    "C♭m": ["C♭", "D♭", "E♭♭", "F♭", "G♭", "A♭♭", "B♭♭"],
    D: ["D", "E", "F＃", "G", "A", "B", "C＃"],
    Dm: ["D", "E", "F", "G", "A", "B♭", "C"],
    "D＃": ["D＃", "E＃", "F＃＃", "G＃", "A＃", "B＃", "C＃＃"],
    "D＃m": ["D＃", "E＃", "F＃", "G＃", "A＃", "B", "C＃"],
    "D♭": ["D♭", "E♭", "F", "G♭", "A♭", "B♭", "C"],
    "D♭m": ["D♭", "E♭", "F♭", "G♭", "A♭", "B♭♭", "C♭"],
    E: ["E", "F＃", "G＃", "A", "B", "C＃", "D＃"],
    Em: ["E", "F＃", "G", "A", "B", "C", "D"],
    "E＃": ["E＃", "F＃＃", "G＃＃", "A＃", "B＃", "C＃＃", "D＃＃"],
    "E＃m": ["E＃", "F＃＃", "G＃", "A＃", "B＃", "C＃", "D＃"],
    "E♭": ["E♭", "F", "G", "A♭", "B♭", "C", "D"],
    "E♭m": ["E♭", "F", "G♭", "A♭", "B♭", "C♭", "D♭"],
    F: ["F", "G", "A", "B♭", "C", "D", "E"],
    Fm: ["F", "G", "A♭", "B♭", "C", "D♭", "E♭"],
    "F＃": ["F＃", "G＃", "A＃", "B", "C＃", "D＃", "E＃"],
    "F＃m": ["F＃", "G＃", "A", "B", "C＃", "D", "E"],
    "F♭": ["F♭", "G♭", "A♭", "B♭♭", "C♭", "D♭", "E♭"],
    "F♭m": ["F♭", "G♭", "A♭♭", "B♭♭", "C♭", "D♭♭", "E♭♭"],
    G: ["G", "A", "B", "C", "D", "E", "F＃"],
    Gm: ["G", "A", "B♭", "C", "D", "E♭", "F"],
    "G＃": ["G＃", "A＃", "B＃", "C＃", "D＃", "E＃", "F＃＃"],
    "G＃m": ["G＃", "A＃", "B", "C＃", "D＃", "E", "F＃"],
    "G♭": ["G♭", "A♭", "B♭", "C♭", "D♭", "E♭", "F"],
    "G♭m": ["G♭", "A♭", "B♭♭", "C♭", "D♭", "E♭♭", "F♭"],
    A: ["A", "B", "C＃", "D", "E", "F＃", "G＃"],
    Am: ["A", "B", "C", "D", "E", "F", "G"],
    "A＃": ["A＃", "B＃", "C＃＃", "D＃", "E＃", "F＃＃", "G＃＃"],
    "A＃m": ["A＃", "B＃", "C＃", "D＃", "E＃", "F＃", "G＃"],
    "A♭": ["A♭", "B♭", "C", "D♭", "E♭", "F", "G"],
    "A♭m": ["A♭", "B♭", "C♭", "D♭", "E♭", "F♭", "G♭"],
    B: ["B", "C＃", "D＃", "E", "F＃", "G＃", "A＃"],
    Bm: ["B", "C＃", "D", "E", "F＃", "G", "A"],
    "B＃": ["B＃", "C＃＃", "D＃＃", "E＃", "F＃＃", "G＃＃", "A＃＃"],
    "B＃m": ["B＃", "C＃＃", "D＃", "E＃", "F＃＃", "G＃", "A＃"],
    "B♭": ["B♭", "C", "D", "E♭", "F", "G", "A"],
    "B♭m": ["B♭", "C", "D♭", "E♭", "F", "G♭", "A♭"],
  };
  return scaleMap[scale] || [];
};

export const getScaleDiatonicChords = (scale: string) => {
  const scaleDiatonicChordMap: { [key: string]: string[] } = {
    C: ["C", "Dm", "Em", "F", "G", "Am", "Bdim"],
    Cm: ["Cm", "Ddim", "E♭", "Fm", "Gm", "A♭", "B♭"],
    "C＃": ["C＃", "D＃m", "Fm", "F＃", "G＃", "A＃m", "Cdim"],
    "C＃m": ["C＃m", "D＃dim", "E", "F＃m", "G＃m", "A", "B"],
    "C♭": ["C♭", "D♭m", "E♭m", "F♭", "G♭", "A♭m", "B♭dim"],
    "C♭m": ["C♭m", "D♭dim", "E♭♭", "F♭m", "G♭m", "A♭♭", "B♭♭"],
    D: ["D", "Em", "F＃m", "G", "A", "Bm", "C＃dim"],
    Dm: ["Dm", "Edim", "F", "Gm", "Am", "B♭", "C"],
    "D＃": ["D＃", "Fm", "Gm", "G＃", "A＃", "Cm", "Ddim"],
    "D＃m": ["D＃m", "Fdim", "F＃", "G＃m", "A＃m", "B", "C＃"],
    "D♭": ["D♭", "E♭m", "Fm", "G♭", "A♭", "B♭m", "Cdim"],
    "D♭m": ["D♭m", "E♭dim", "F♭", "G♭m", "A♭m", "B♭♭", "C♭"],
    E: ["E", "F＃m", "G＃m", "A", "B", "C＃m", "D＃dim"],
    Em: ["Em", "F＃dim", "G", "Am", "Bm", "C", "D"],
    "E＃": ["E＃", "F＃＃m", "G＃＃m", "A＃", "B＃", "C＃＃m", "D＃＃dim"],
    "E＃m": ["E＃m", "F＃＃dim", "G＃", "A＃m", "B＃m", "C＃", "D＃"],
    "E♭": ["E♭", "Fm", "Gm", "A♭", "B♭", "Cm", "Ddim"],
    "E♭m": ["E♭m", "Fdim", "G♭", "A♭m", "B♭m", "C♭", "D♭"],
    F: ["F", "Gm", "Am", "B♭", "C", "Dm", "Edim"],
    Fm: ["Fm", "Gdim", "A♭", "B♭m", "Cm", "D♭", "E♭"],
    "F＃": ["F＃", "G＃m", "A＃m", "B", "C＃", "D＃m", "E＃dim"],
    "F＃m": ["F＃m", "G＃dim", "A", "Bm", "C＃m", "D", "E"],
    "F♭": ["F♭", "G♭m", "A♭m", "B♭♭", "C♭", "D♭m", "E♭dim"],
    "F♭m": ["F♭m", "G♭dim", "A♭♭", "B♭♭m", "C♭m", "D♭♭", "E♭♭"],
    G: ["G", "Am", "Bm", "C", "D", "Em", "F＃dim"],
    Gm: ["Gm", "Adim", "B♭", "Cm", "Dm", "E♭", "F"],
    "G＃": ["G＃", "A＃m", "Cm", "C＃", "D＃", "Fm", "Gdim"],
    "G＃m": ["G＃m", "A＃dim", "B", "C＃m", "D＃m", "E", "F＃"],
    "G♭": ["G♭", "A♭m", "B♭m", "C♭", "D♭", "E♭m", "Fdim"],
    "G♭m": ["G♭m", "A♭dim", "B♭♭", "C♭m", "D♭m", "E♭♭", "F♭"],
    A: ["A", "Bm", "C＃m", "D", "E", "F＃m", "G＃dim"],
    Am: ["Am", "Bdim", "C", "Dm", "Em", "F", "G"],
    "A＃": ["A＃", "Cm", "Dm", "D＃", "F", "Gm", "Adim"],
    "A＃m": ["A＃m", "Cdim", "C＃", "D＃m", "Fm", "F＃", "G＃"],
    "A♭": ["A♭", "B♭m", "Cm", "D♭", "E♭", "Fm", "Gdim"],
    "A♭m": ["A♭m", "B♭dim", "C♭", "D♭m", "E♭m", "F♭", "G♭"],
    B: ["B", "C＃m", "D＃m", "E", "F＃", "G＃m", "A＃dim"],
    Bm: ["Bm", "C＃dim", "D", "Em", "F＃m", "G", "A"],
    "B＃": ["B＃", "C＃＃m", "D＃＃m", "E＃", "F＃＃", "G＃＃m", "A＃＃dim"],
    "B＃m": ["B＃m", "C＃＃dim", "D＃", "E＃m", "F＃＃m", "G＃", "A＃"],
    "B♭": ["B♭", "Cm", "Dm", "E♭", "F", "Gm", "Adim"],
    "B♭m": ["B♭m", "Cdim", "D♭", "E♭m", "Fm", "G♭", "A♭"],
  };
  return scaleDiatonicChordMap[scale] || [];
};

export const getScaleDiatonicChordsWith7th = (scale: string) => {
  const scaleDiatonicChord7thMap: { [key: string]: string[] } = {
    C: ["Cmaj7", "Dm7", "Em7", "Fmaj7", "G7", "Am7", "Bm7♭5"],
    Cm: ["Cm(maj7)", "Dm7♭5", "E♭maj7", "Fm7", "Gm7", "A♭maj7", "B♭7"],
    "C＃": ["C＃maj7", "D＃m7", "Fm7", "F＃maj7", "G＃7", "A＃m7", "C7"],
    "C＃m": ["C＃m(maj7)", "D＃m7♭5", "Emaj7", "F＃m7", "G＃m7", "Amaj7", "B7"],
    "C♭": ["C♭maj7", "D♭m7", "E♭m7", "F♭maj7", "G♭7", "A♭m7", "B♭m7♭5"],
    "C♭m": ["C♭m(maj7)", "D♭m7♭5", "E♭♭maj7", "F♭m7", "G♭m7", "A♭♭maj7", "B♭♭7"],
    D: ["Dmaj7", "Em7", "F＃m7", "Gmaj7", "A7", "Bm7", "C＃m7♭5"],
    Dm: ["Dm(maj7)", "Em7♭5", "Fmaj7", "Gm7", "Am7", "B♭maj7", "C7"],
    "D＃": ["D＃maj7", "Fm7", "Gm7", "G＃maj7", "A＃7", "Cm7", "D7"],
    "D＃m": ["D＃m(maj7)", "Fm7♭5", "F＃maj7", "G＃m7", "A＃m7", "Bmaj7", "C＃7"],
    "D♭": ["D♭maj7", "E♭m7", "Fm7", "G♭maj7", "A♭7", "B♭m7", "C7"],
    "D♭m": ["D♭m(maj7)", "E♭m7♭5", "F♭maj7", "G♭m7", "A♭m7", "B♭♭maj7", "C♭7"],
    E: ["Emaj7", "F＃m7", "G＃m7", "Amaj7", "B7", "C＃m7", "D＃m7♭5"],
    Em: ["Em(maj7)", "F＃m7♭5", "Gmaj7", "Am7", "Bm7", "Cmaj7", "D7"],
    "E＃": ["E＃maj7", "F＃＃m7", "G＃＃m7", "A＃maj7", "B＃7", "C＃＃m7", "D＃＃m7♭5"],
    "E＃m": ["E＃m(maj7)", "F＃＃m7♭5", "G＃maj7", "A＃m7", "B＃m7", "C＃maj7", "D＃7"],
    "E♭": ["E♭maj7", "Fm7", "Gm7", "A♭maj7", "B♭7", "Cm7", "Dm7♭5"],
    "E♭m": ["E♭m(maj7)", "Fm7♭5", "G♭maj7", "A♭m7", "B♭m7", "C♭maj7", "D♭7"],
    F: ["Fmaj7", "Gm7", "Am7", "B♭maj7", "C7", "Dm7", "Em7♭5"],
    Fm: ["Fm(maj7)", "Gm7♭5", "A♭maj7", "B♭m7", "Cm7", "D♭maj7", "E♭7"],
    "F＃": ["F＃maj7", "G＃m7", "A＃m7", "Bmaj7", "C＃7", "D＃m7", "E＃m7♭5"],
    "F＃m": ["F＃m(maj7)", "G＃m7♭5", "Amaj7", "Bm7", "C＃m7", "Dmaj7", "E7"],
    "F♭": ["F♭maj7", "G♭m7", "A♭m7", "B♭♭maj7", "C♭7", "D♭m7", "E♭m7♭5"],
    "F♭m": ["F♭m(maj7)", "G♭m7♭5", "A♭♭maj7", "B♭♭m7", "C♭m7", "D♭♭maj7", "E♭♭7"],
    G: ["Gmaj7", "Am7", "Bm7", "Cmaj7", "D7", "Em7", "F＃m7♭5"],
    Gm: ["Gm(maj7)", "Am7♭5", "B♭maj7", "Cm7", "Dm7", "E♭maj7", "F7"],
    "G＃": ["G＃maj7", "A＃m7", "Cm7", "C＃maj7", "D＃7", "Fm7", "Gm7♭5"],
    "G＃m": ["G＃m(maj7)", "A＃m7♭5", "Bmaj7", "C＃m7", "D＃m7", "Emaj7", "F＃7"],
    "G♭": ["G♭maj7", "A♭m7", "B♭m7", "C♭maj7", "D♭7", "E♭m7", "Fm7♭5"],
    "G♭m": ["G♭m(maj7)", "A♭m7♭5", "B♭♭maj7", "C♭m7", "D♭m7", "E♭♭maj7", "F♭7"],
    A: ["Amaj7", "Bm7", "C＃m7", "Dmaj7", "E7", "F＃m7", "G＃m7♭5"],
    Am: ["Am(maj7)", "Bm7♭5", "Cmaj7", "Dm7", "Em7", "Fmaj7", "G7"],
    "A＃": ["A＃maj7", "Cm7", "Dm7", "D＃maj7", "F7", "Gm7", "Am7♭5"],
    "A＃m": ["A＃m(maj7)", "Cm7♭5", "C＃maj7", "D＃m7", "Fm7", "F＃maj7", "G＃7"],
    "A♭": ["A♭maj7", "B♭m7", "Cm7", "D♭maj7", "E♭7", "Fm7", "Gm7♭5"],
    "A♭m": ["A♭m(maj7)", "B♭m7♭5", "C♭maj7", "D♭m7", "E♭m7", "F♭maj7", "G♭7"],
    B: ["Bmaj7", "C＃m7", "D＃m7", "Emaj7", "F＃7", "G＃m7", "A＃m7♭5"],
    Bm: ["Bm(maj7)", "C＃m7♭5", "Dmaj7", "Em7", "F＃m7", "Gmaj7", "A7"],
    "B＃": ["B＃maj7", "C＃＃m7", "D＃＃m7", "E＃maj7", "F＃＃7", "G＃＃m7", "A＃＃m7♭5"],
    "B＃m": ["B＃m(maj7)", "C＃＃m7♭5", "D＃maj7", "E＃m7", "F＃＃m7", "G＃maj7", "A＃7"],
    "B♭": ["B♭maj7", "Cm7", "Dm7", "E♭maj7", "F7", "Gm7", "Am7♭5"],
    "B♭m": ["B♭m(maj7)", "Cm7♭5", "D♭maj7", "E♭m7", "Fm7", "G♭maj7", "A♭7"],
  };
  return scaleDiatonicChord7thMap[scale] || [];
};

export const scaleText = (scale: string) => {
  const scaleMap: { [key: string]: string } = {
    C: "C Major",
    Cm: "C Minor",
    "C＃": "C＃ Major",
    "C＃m": "C＃ Minor",
    "C♭": "C♭ Major",
    "C♭m": "C♭ Minor",
    D: "D Major",
    Dm: "D Minor",
    "D＃": "D＃ Major",
    "D＃m": "D＃ Minor",
    "D♭": "D♭ Major",
    "D♭m": "D♭ Minor",
    E: "E Major",
    Em: "E Minor",
    "E＃": "E＃ Major",
    "E＃m": "E＃ Minor",
    "E♭": "E♭ Major",
    "E♭m": "E♭ Minor",
    F: "F Major",
    Fm: "F Minor",
    "F＃": "F＃ Major",
    "F＃m": "F＃ Minor",
    "F♭": "F♭ Major",
    "F♭m": "F♭ Minor",
    G: "G Major",
    Gm: "G Minor",
    "G＃": "G＃ Major",
    "G＃m": "G＃ Minor",
    "G♭": "G♭ Major",
    "G♭m": "G♭ Minor",
    A: "A Major",
    Am: "A Minor",
    "A＃": "A＃ Major",
    "A＃m": "A＃ Minor",
    "A♭": "A♭ Major",
    "A♭m": "A♭ Minor",
    B: "B Major",
    Bm: "B Minor",
    "B＃": "B＃ Major",
    "B＃m": "B＃ Minor",
    "B♭": "B♭ Major",
    "B♭m": "B♭ Minor",
  };
  return `${scaleMap[scale]} Scale` || scale;
};
